### ISSUE TITLE
我想请问一下SampleData中的数据字段含义

### ISSUE THREAD

**Issue by Rakouga** [zyphs21/HSStockChart#1]
作者你好，我个人一直很关注您的HSStockChart项目，非常简洁但是功能齐全，我觉得比那些几个百fork的K线图项目还好用。
不过我在使用的过程中遇到了一个小问题，就是股票数据中（SZ300033.json）中股票数据我不清楚其字段含义，如“redeem_type”、“issue_type”，以至于我无法使用我这边的数据替换使用。
如果可以的话，请告诉我您的股票数据来源于哪个api，我可以自己去查一下字段的含义，然后我会帮忙将注释过的股票数据push给你。

**Comment by zyphs21** [comment]
@Rakouga 你好，这个SZ300033.json是抓 雪球app 的数据包拿到的json数据，但是代码里其实只用了"name" 和 "last_close"这两个字段。现在我还在不断地修正和增加这个项目的功能，迟点我会push最新的代码上来，有问题我们可以到时再讨论。

**Comment by zyphs21** [comment]
@Rakouga  Hello，HSStockChart had been modified a lot, feel free to check it out. I'll close this issue for now.

**Comment by topws** [comment]
@zyphs21 追问一句，KLine的JSON数据中，chartList有很多个字段，除了"open","close","ma"这些比较明显的含义外，其他的字段能不能注释下。另外想问下Y轴的坐标是不是跟某个值有关系，而不是自定义的？

**Comment by zyphs21** [comment]
Hello，this is the Chinese explanation：

字段 | 含义
---- | ---
volume | 交易量
open | 开盘价
high | 最高价
close | 收盘价
low | 最低价
chg | 涨跌值
percent | 涨跌幅
turnrate | 换手率
ma5 | 5日移动平均
ma10 | 10日移动平均
ma20 | 20日移动平均
ma30 | 30日移动平均
dif | 离差值
dea | 离差平均值
macd | 移动平均聚散指标
time | 时间

**Comment by topws** [comment]
非常感谢，上面还有一个小问题，因为数据涉及很广，有0.00001,也有1000000，所以我想知道Y轴的坐标是如何定义的？因为差值可能很小，所以想自己定义

**Comment by zyphs21** [comment]
@topws Y轴坐标的值是通过当前显示片段中的数据里找出最大值和最小值来确定的。

**Comment by topws** [comment]
嗯谢谢，这个我已经看到了，就是想偷懒问下，具体的设置值在哪里？（因为我想添加 分K图，X轴需要自定义，Y轴的数据我也要定义下，保留两位小数点不够我需要自己再判断）
<img width="113" alt="60df9b32-785a-45cd-9cb9-cfcf02fb26a3" src="https://user-images.githubusercontent.com/16485279/43708238-99fdb574-999c-11e8-9759-80ad9af8c6e1.png">

**Comment by zyphs21** [comment]
@topws 在这个方法：[HSKLine.swift#L124](https://github.com/zyphs21/HSStockChart/blob/7d46be703f4f97330f891fbd3eeaf63b5dc64a03/HSStockChart/Classes/KLineChart/HSKLine.swift#L124)

**Comment by topws** [comment]
OK，THKS

**Comment by zyphs21** [comment]
@Rakouga @topws  关于数据字段的含义我把它放到 [Wiki](https://github.com/zyphs21/HSStockChart/wiki) 里了。所以这个 issue 就再次 close 掉了。
