### ISSUE TITLE
分时图不支持左右滑动

### ISSUE THREAD

**Issue by mouse-lin** [zyphs21/HSStockChart#12]

**Comment by zyphs21** [comment]
你好，一般来说，分时图的展示是不需要滑动，它展示的是固定时间段的数据。

**Comment by mouse-lin** [comment]
@zyphs21 哈，我在实现的时候发现有些需求需要展示滑动，例如全天24小时都需要交易的情况下，所以我就自己动手改了下实现了，哈哈

**Comment by zyphs21** [comment]
@mouse-lin 你好，如果没什么问题的话，我先关闭这个issue了。
