### ISSUE TITLE
Why cannot I see all the Info?

### ISSUE THREAD

**Issue by andfans** [zyphs21/HSStockChart#4]
![2017-02-24 12 26 40](https://cloud.githubusercontent.com/assets/23206215/23290566/b78bb146-fa8c-11e6-8bda-ffab138db7b9.png)

**Comment by zyphs21** [comment]
@andfans It works fine when I run in simulator(iOS10 iPhone7 as show in your screenshot)

**Comment by andfans** [comment]
It show like this when I run in simulator(iOS10 iPhone7,6s,5s) and in real iPhone7(iOS10.2.1).I never change anything.
![img_0117](https://cloud.githubusercontent.com/assets/23206215/23329760/67c06dd0-fb79-11e6-8f84-9a635e63055c.PNG)

**Comment by zyphs21** [comment]
@andfans It is really odd. It works fine when I run it. I suggest you make some breakpoint to debug it, or you can clone it again.

**Comment by zyphs21** [comment]
@andfans Hello, HSStockChart had been modified a lot. Do you still have this problem? I temporarily close this issue.
